interface IProduct {
  id: number;
  title: string;
  description: string;
  discountPrecentage: number;
  raiting: number;
  stock: number;
  price: number;
  brand: string;
  category: string;
  previewImg: string;
  images: Array<string>;
}

export const PRODUCTS: Array<IProduct> = [
  {
    id: 1,
    title: 'Airpods 2',
    description: 'Airpods Pro 2 — новые bluetooth наушники Apple, представленные компанией в сентябре 2022. Гаджет вызвал большой интерес благодаря безупречным характеристикам. Эти параметры сочетаются с выгодными условиями продажи Airpods Pro 2',
    discountPrecentage: 5.5,
    raiting: 4.84,
    stock: 40,
    price: 200,
    brand: 'Apple',
    category: "Headphones",
    previewImg: '/catalog-img/headphones/apple/Airpods 2/Airpods 2-1.jpg',
    images: ['./catalog-img/headphones/apple/Airpods 2/Airpods 2-1.jpg', 
    './catalog-img/headphones/apple/Airpods 2/Airpods 2-2.jpg', 
    './catalog-img/headphones/apple/Airpods 2/Airpods 2-3.jpg'],
  },
  {
    id: 2,
    title: 'AirPods 3',
    description: 'AirPods 3 - это новейшие AirPods от Apple с более компактной штангой, переработанным контуром, адаптивным эквалайзером, устойчивостью к поту, поддержкой пространственного звука, меньшими штангами, футляром для зарядки MagSafe, адаптивным эквалайзером, до 30 часов автономной работы, защитой от воды и пота IPX4, пространственным звуком. Звонки HD FaceTime',
    discountPrecentage: 5,
    raiting: 4.8,
    stock: 50,
    price: 210,
    brand: 'Apple',
    category: "Headphones",
    previewImg: './catalog-img/headphones/apple/AirPods 3/Apple AirPods 3-1.jpg',
    images: ['./catalog-img/headphones/apple/AirPods 3/Apple AirPods 3-1.jpg', 
    './catalog-img/headphones/apple/AirPods 3/Apple AirPods 3-2.jpg', 
    './catalog-img/headphones/apple/AirPods 3/Apple AirPods 3-3.jpg'],
  },
  {
    id: 3,
    title: 'Samsung Galaxy Buds 2',
    description: 'Новые беспроводные наушники от Samsung Galaxy Buds 2, наряду со смартфонами, смогли также быстро завоевать доверие среди своих пользователей. Ничего сверхсложного - только стильный дизайн, качественный звук и при этом доступная цена в совокупности дают нам успех. Наушники Samsung Galaxy Buds 2 подключаются через Bluetooth 5.2 и легко синхронизируются с любыми новейшими устройствами - как версии Android, так и iOS. С помощью специального приложения Buds Manager, в свою очередь, можно использовать функцию «Easy Pairing» для быстрого подключения наушников и их управления на компьютере.',
    discountPrecentage: 10,
    raiting: 3.9,
    stock: 75,
    price: 150,
    brand: 'Samsung',
    category: "Headphones",
    previewImg: './catalog-img/headphones/samsung/Samsung Galaxy Buds 2/Samsung Galaxy Buds 2-1.jpg',
    images: ['./catalog-img/headphones/samsung/Samsung Galaxy Buds 2/Samsung Galaxy Buds 2-1.jpg', 
    './catalog-img/headphones/samsung/Samsung Galaxy Buds 2/Samsung Galaxy Buds 2-2.jpg', 
    './catalog-img/headphones/samsung/Samsung Galaxy Buds 2/Samsung Galaxy Buds 2-3.jpg'],
  },
  {
    id: 4,
    title: 'Samsung Galaxy Buds Pro',
    description: 'Это беспроводные наушники с технологиями профессионального уровня, обеспечивающими невероятное погружение в захватывающий звук. При этом интеллектуальное активное шумоподавление позволяет плавно переключаться между максимальным устранением внешних шумов и режимом окружающего звука для контроля за происходящим вокруг. Так что, впускать внешний мир внутрь или оставить его снаружи - выбор за вами. Это ваш мир. С наушниками Galaxy Buds Pro вы услышите только самое лучшее. Технология активного шумоподавления в наушниках Galaxy Buds Pro устраняет до 99% внешних шумов. Микрофоны внутри и снаружи отслеживают шум в режиме реального времени.',
    discountPrecentage: 8.5,
    raiting: 4.3,
    stock: 45,
    price: 170,
    brand: 'Samsung',
    category: "Headphones",
    previewImg: './catalog-img/headphones/samsung/Samsung Galaxy Buds 2/Samsung Galaxy Buds Pro-1.jpg',
    images: ['./catalog-img/headphones/samsung/Samsung Galaxy Buds 2/Samsung Galaxy Buds Pro-1.jpg', 
    './catalog-img/headphones/samsung/Samsung Galaxy Buds 2/Samsung Galaxy Buds Pro-2.jpg', 
    './catalog-img/headphones/samsung/Samsung Galaxy Buds 2/Samsung Galaxy Buds Pro-3.jpg'],
  },
  {
    id: 5,
    title: 'TWS F-9',
    description: 'Беспроводные наушники с цифровым зарядным павербанком  TWS F9  Bluetooth 5.0. Наушники изготовлены из качественных и приятных на ощупь материалов, не раздражающих кожу во время длительного использования и занятия спортом, имеют цифровой дисплей. При этом, они  легкие и компактные, имеют удобный футляр с павербанком. Идеально подходят для повседневного использования и спорта.',
    discountPrecentage: 7.5,
    raiting: 3.74,
    stock: 90,
    price: 50,
    brand: 'Xiaomi',
    category: "Headphones",
    previewImg: './catalog-img/headphones/xiaomi/F9/F9-1.jpg',
    images: ['./catalog-img/headphones/xiaomi/F9/F9-1.jpg', 
    './catalog-img/headphones/xiaomi/F9/F9-2.jpg', 
    './catalog-img/headphones/xiaomi/F9/F9-3.jpg'],
  },
  {
    id: 6,
    title: 'TWS i100',
    description: 'Наушники i100 tws легко и быстро подключаются через Bluetooth к смартфону, планшету или ноутбуку, при этом радиус действия устройства позволяет отдаляться до 10м от источника, сохраняя стабильное соединение. Одним из главных преимуществ Bluetooth-наушников i100 является качественное воспроизведение записи, насыщенный, четкий звук, а также глубокие приятные басы, все это подарит наслаждение от прослушивания музыки даже самым требовательным меломанам. Наушники i100 tws отлично работают и в качестве гарнитуры, ваши собеседники услышат четко и ясно каждое сказанное слово. Кроме того, благодаря мощной системе активного шумоподавления, вы сможете ощутить качество воспроизведения в полном объеме.',
    discountPrecentage: 8.5,
    raiting: 3.72,
    stock: 70,
    price: 75,
    brand: 'Xiaomi',
    category: "Headphones",
    previewImg: './catalog-img/headphones/xiaomi/i100/i100-1.jpg',
    images: ['./catalog-img/headphones/xiaomi/i100/i100-1.jpg', 
    './catalog-img/headphones/xiaomi/i100/i100-2.jpg', 
    './catalog-img/headphones/xiaomi/i100/i100-3.jpg'],
  },
  {
    id: 7,
    title: 'Apple MacBook Pro 13',
    description: 'Ноутбук Apple MacBook Pro 13 оснащён мощным 4-ядерным процессором и 16 Гб оперативной памяти, что гарантирует отличное быстродействие. Дисплей IPS Retina с разрешением 2560x1600 поразит вас яркими, сочными красками. Ноутбук поддерживает стандарт Wi-Fi 802.11ac, который обеспечивает высокую скорость интернета.',
    discountPrecentage: 4,
    raiting: 4.6,
    stock: 20,
    price: 1700,
    brand: 'Apple',
    category: "Laptop",
    previewImg: './catalog-img/laptop/apple/Apple MacBook Pro 13/Apple MacBook Pro 13-1.png',
    images: ['./catalog-img/laptop/apple/Apple MacBook Pro 13/Apple MacBook Pro 13-1.png', 
    './catalog-img/laptop/apple/Apple MacBook Pro 13/Apple MacBook Pro 13-2.png', 
    './catalog-img/laptop/apple/Apple MacBook Pro 13/Apple MacBook Pro 13-3.png',
    './catalog-img/laptop/apple/Apple MacBook Pro 13/Apple MacBook Pro 13-4.png'],
  },
  {
    id: 8,
    title: 'Apple Macbook Pro 14',
    description: 'Чип Apple M1 Pro. десятиядерный процессор с 8 ядрами производительности и 2 ядрами эффективности шестнадцатиядерный графический процессор шестнадцатиядерная система Neural Engine. Пропускная способность памяти: 200 ГБ/﻿с Медиапроцессор H.264, HEVC, ProRes и ProRes RAW с аппаратным ускорением',
    discountPrecentage: 5,
    raiting: 4.7,
    stock: 10,
    price: 2500,
    brand: 'Apple',
    category: "Laptop",
    previewImg: './catalog-img/laptop/apple/Apple MacBook Pro 14/Apple MacBook Pro 13-1.png',
    images: ['./catalog-img/laptop/apple/Apple MacBook Pro 14/Apple MacBook Pro 13-1.png', 
    './catalog-img/laptop/apple/Apple MacBook Pro 14/Apple MacBook Pro 13-2.png', 
    './catalog-img/laptop/apple/Apple MacBook Pro 14/Apple MacBook Pro 13-3.png',
    './catalog-img/laptop/apple/Apple MacBook Pro 14/Apple MacBook Pro 13-4.png'],
  },
  {
    id: 9,
    title: 'Apple Macbook Pro 16',
    description: 'В середине ноября 2019-го Apple представила долгожданную новинку — 16-дюймовый MacBook Pro. Слухи о ней ходили еще с лета, и вот, наконец, устройство поступило в продажу. Особое внимание к нему закономерно. Во-первых, Apple впервые использует такую диагональ экрана: до настоящего момента самой крупной моделью в линейке ноутбуков была 15-дюймовая, а еще раньше, вплоть до 2012 года, можно было купить 17-дюймовую «прошку». Но 16 дюймов не было никогда. И во-вторых, это не только самый крупный на сегодняшний день, но и самый мощный MacBook Pro: здесь процессор Intel Core i9 и дискретная графика, чего нет в 13-дюймовых моделях.',
    discountPrecentage: 11,
    raiting: 4.9,
    stock: 8,
    price: 4000,
    brand: 'Apple',
    category: "Laptop",
    previewImg: './catalog-img/laptop/apple/Apple MacBook Pro 16/Apple Macbook Pro 16-1.png',
    images: ['./catalog-img/laptop/apple/Apple MacBook Pro 16/Apple Macbook Pro 16-1.png', 
    './catalog-img/laptop/apple/Apple MacBook Pro 16/Apple Macbook Pro 16-2.png', 
    './catalog-img/laptop/apple/Apple MacBook Pro 16/Apple Macbook Pro 16-3.png',
    './catalog-img/laptop/apple/Apple MacBook Pro 16/Apple Macbook Pro 16-4.png'],
  },
  {
    id: 10,
    title: 'Huawei MateBook D 15',
    description: '«Космический серый» стал фирменным цветом ноутбуков Huawei, поскольку новый Huawei MateBook D 15 (2021), как и его предшественники, выпущен именно в этом цвете. Поэтому выглядит ноутбук неброско, но и не сказать, что скучно, тем более что анодированные алюминиевые панели корпуса придают ему более дорогой и изысканный вид, чем если бы это был пластик.',
    discountPrecentage: 15,
    raiting: 3.6,
    stock: 30,
    price: 980,
    brand: 'Huawei',
    category: "Laptop",
    previewImg: './catalog-img/laptop/huawei/Huawei MateBook D 15/Huawei MateBook D 15-1.jpg',
    images: ['./catalog-img/laptop/huawei/Huawei MateBook D 15/Huawei MateBook D 15-1.jpg',
    './catalog-img/laptop/huawei/Huawei MateBook D 15/Huawei MateBook D 15-2.jpg',
    './catalog-img/laptop/huawei/Huawei MateBook D 15/Huawei MateBook D 15-3.jpg'],
  },
  {
    id: 11,
    title: 'Huawei MateBook D 16',
    description: '16-дюймовый ноутбук со «взрослым» процессором Intel серии H весит 1,7 кг. Многие компьютеры с меньшими экранами и более слабыми чипами весят от 2 кг. Отдельно стоит отметить блок питания: он похож на зарядку для смартфона и весит меньше 200 граммов. «Кирпич» от сравнимого по характеристикам Lenovo Ideapad 5 со всеми проводами весит примерно полкилограмма, и носить его с собой не так удобно.',
    discountPrecentage: 12,
    raiting: 3.7,
    stock: 40,
    price: 1020,
    brand: 'Huawei',
    category: "Laptop",
    previewImg: './catalog-img/laptop/huawei/Huawei MateBook D 16/Huawei MateBook D 16-1.jpg',
    images: ['./catalog-img/laptop/huawei/Huawei MateBook D 16/Huawei MateBook D 16-1.jpg',
    './catalog-img/laptop/huawei/Huawei MateBook D 16/Huawei MateBook D 16-2.jpg',
    './catalog-img/laptop/huawei/Huawei MateBook D 16/Huawei MateBook D 16-3.jpg'],
  },
  {
    id: 12,
    title: 'Lenovo IdeaPad 1 14ADA05',
    description: 'Lenovo ideapad 1 14ADA05 оснащен 4-потоковым процессором AMD Athlon Silver 3050e с тактовой частотой 1,4–2,8 ГГц. В ноутбуке установлены оперативная память DDR4 объемом 4 ГБ и интегрированная видеокарта AMD Radeon Graphics. Такой производительности вполне достаточно для решения повседневных задач: обучайся и работай, общайся с семьей и друзьями, следи за актуальными мировыми новостями.',
    discountPrecentage: 11,
    raiting: 2.8,
    stock: 10,
    price: 220,
    brand: 'Lenovo',
    category: "Laptop",
    previewImg: './catalog-img/laptop/lenovo/Lenovo IdeaPad 1 14ADA05/Lenovo IdeaPad 1 14ADA05-1.jpg',
    images: ['./catalog-img/laptop/lenovo/Lenovo IdeaPad 1 14ADA05/Lenovo IdeaPad 1 14ADA05-1.jpg',
    './catalog-img/laptop/lenovo/Lenovo IdeaPad 1 14ADA05/Lenovo IdeaPad 1 14ADA05-2.jpg',
    './catalog-img/laptop/lenovo/Lenovo IdeaPad 1 14ADA05/Lenovo IdeaPad 1 14ADA05-3.jpg',
    './catalog-img/laptop/lenovo/Lenovo IdeaPad 1 14ADA05/Lenovo IdeaPad 1 14ADA05-4.jpg',],
  },
  {
    id: 13,
    title: 'Lenovo IdeaPad 5 Pro',
    description: 'Ноутбук IdeaPad 5 Pro Gen 6 (14, AMD) с дисплеем 2,8K (в максимальной комплектации), оптимизированный для потоковой передачи контента и развлечений, обеспечивает потрясающее качество изображения. Производительные процессоры AMD Ryzen™ обеспечивают прекрасные показатели работы, а технология Dolby Atmos® позволяет насладиться насыщенным реалистичным и объемным звучанием. Тщательно продуманная клавиатура с подсветкой и мягким ходом клавиш, вместе с широкой сенсорной панелью обеспечивает точность и приятную отдачу нажатия.',
    discountPrecentage: 20,
    raiting: 3.0,
    stock: 25,
    price: 700,
    brand: 'Lenovo',
    category: "Laptop",
    previewImg: './catalog-img/laptop/lenovo/Lenovo IdeaPad 5 Pro/Lenovo IdeaPad 5 Pro-1.jpg',
    images: ['./catalog-img/laptop/lenovo/Lenovo IdeaPad 5 Pro/Lenovo IdeaPad 5 Pro-1.jpg',
    './catalog-img/laptop/lenovo/Lenovo IdeaPad 5 Pro/Lenovo IdeaPad 5 Pro-2.jpg',
    './catalog-img/laptop/lenovo/Lenovo IdeaPad 5 Pro/Lenovo IdeaPad 5 Pro-3.jpg',
    './catalog-img/laptop/lenovo/Lenovo IdeaPad 5 Pro/Lenovo IdeaPad 5 Pro-4.jpg',],
  },
  {
    id: 14,
    title: 'Lenovo V14-ADA',
    description: 'Мощный и эргономичный ноутбук для работы - первая необходимость для любого офисного сотрудника или самозанятого. И если раньше выбор устройств для малого и среднего бизнеса ограничивался определенным рядом ультрабуков на базе платформы Intel, то сегодня рынок завоевывают более доступные, но не менее производительные модели с энергоэффективным железом от AMD. Оптимальным вариантом по соотношению цены и производительности являются ультрабуки на базе новейших мобильных процессоров AMD Ryzen 5000-й серии, представленных в 2021 г. Один из них, модель Lenovo V14-ADA.',
    discountPrecentage: 10,
    raiting: 3.8,
    stock: 50,
    price: 550,
    brand: 'Lenovo',
    category: "Laptop",
    previewImg: './catalog-img/laptop/lenovo/Lenovo V14-ADA/Lenovo V14-ADA-1.jpg',
    images: ['./catalog-img/laptop/lenovo/Lenovo V14-ADA/Lenovo V14-ADA-1.jpg',
    './catalog-img/laptop/lenovo/Lenovo V14-ADA/Lenovo V14-ADA-2.jpg',
    './catalog-img/laptop/lenovo/Lenovo V14-ADA/Lenovo V14-ADA-3.jpg'],
  },
  {
    id: 15,
    title: 'Iphone 13',
    description: 'Общие габариты теперь составляют 146,7x71,5x7,65 мм. В весе новая модель тоже чуть-чуть прибавила и теперь это 174 грамма. На эргономичности такие изменения практически не сказались. iPhone 13 все еще не самый громоздкий, но и не из самых маленьких iPhone.',
    discountPrecentage: 8,
    raiting: 4.9,
    stock: 100,
    price: 750,
    brand: 'Apple',
    category: "Phone",
    previewImg: './catalog-img/phones/apple/iphone13/13blue1.jpg',
    images: ['./catalog-img/phones/apple/iphone13/13blue1.jpg',
    './catalog-img/phones/apple/iphone13/13blue2.jpg',
    './catalog-img/phones/apple/iphone13/13blue3.jpg',
    './catalog-img/phones/apple/iphone13/13blue4.jpg',
    './catalog-img/phones/apple/iphone13/13blue5.jpg'],
  },
  {
    id: 16,
    title: 'Iphone 13 Pro',
    description: 'Apple iPhone 13 Pro оснастили OLED-экраном с частотой 120 Гц, обеспечивающие ему высокую плавность работы. Плотность пикселей здесь не рекордная, однако изображение обладает превосходной четкостью. Яркость тоже отличная, так что съемка под яркими лучами солнца не доставит неудобств. Вырез в дисплее стал немного компактнее, а значит его полезная площадь стала больше.',
    discountPrecentage: 4,
    raiting: 4.9,
    stock: 20,
    price: 890,
    brand: 'Apple',
    category: "Phone",
    previewImg: './catalog-img/phones/apple/iphone13pro/iphone13pro-1.jpg',
    images: ['./catalog-img/phones/apple/iphone13pro/iphone13pro-1.jpg',
    './catalog-img/phones/apple/iphone13pro/iphone13pro-2.jpg',
    './catalog-img/phones/apple/iphone13pro/iphone13pro-3.jpg',
    './catalog-img/phones/apple/iphone13pro/iphone13pro-4.jpg',],
  },
  {
    id: 17,
    title: 'Iphone 14',
    description: 'Дисплей Apple iPhone 14 является одним из лучших на рынке по качеству передачи изображения, контрастности и яркости. Он наделен возможностью просмотра HDR-контента благодаря премиальной технологии Dolby Vision. Минимальный уровень яркости достаточно низкий, что ночью экран смартфона не слепил. Единственным существенным недостатком является стандартная частота обновления 60 Гц, тогда как конкуренты имеют минимум 90 Гц. Повышенная частота позитивно сказывается на плавности работы устройства.',
    discountPrecentage: 8,
    raiting: 4.9,
    stock: 50,
    price: 1100,
    brand: 'Apple',
    category: "Phone",
    previewImg: './catalog-img/phones/apple/iphone14pro/iphone14pro-1.jpg',
    images: ['./catalog-img/phones/apple/iphone14pro/iphone14pro-1.jpg',
    './catalog-img/phones/apple/iphone14pro/iphone14pro-2.jpg',
    './catalog-img/phones/apple/iphone14pro/iphone14pro-3.jpg',
    './catalog-img/phones/apple/iphone14pro/iphone14pro-4.jpg',
    './catalog-img/phones/apple/iphone14pro/iphone14pro-5.jpg'],
  },
  {
    id: 18,
    title: 'Huawei P20',
    description: 'Отличительной особенностью Huawei P20 является сенсорная кнопка "Домой" под экраном. Тогда как большинство производителей уже от нее отказались в пользу виртуальной кнопки, данный бренд оставил ее, несмотря на то, что пытался сделать дисплей безрамочным. Благодаря закругленным краям корпуса смартфон лежит в руке, как влитой, но больше всего впечатляют стеклянные панели с обеих сторон, выполненные по технологии Gorilla Glass 5.',
    discountPrecentage: 25,
    raiting: 3.4,
    stock: 55,
    price: 150,
    brand: 'Huawei',
    category: "Phone",
    previewImg: './catalog-img/phones/huawei/huaweiP20/huaweiP20-1.jpg',
    images: ['./catalog-img/phones/huawei/huaweiP20/huaweiP20-1.jpg',
    './catalog-img/phones/huawei/huaweiP20/huaweiP20-2.jpg',
    './catalog-img/phones/huawei/huaweiP20/huaweiP20-3.jpg',
    './catalog-img/phones/huawei/huaweiP20/huaweiP20-4.jpg'],
  },
  {
    id: 19,
    title: 'Huawei P30',
    description: 'Huawei P30 получил OLED-экран, который обеспечивает ему высокое соотношение контраста и рекордную яркость. Это делает смартфон подходящим для использования в солнечную погоду, а благодаря поддержке цветового пространства DCI-P3 цветопередача максимально приближена к естественной. Дисплей может похвастаться защитой в лице прочного стекла Corning Gorilla Glass 6. Оно практически не царапается, поэтому производитель даже не рекомендует использовать сторонние защитные пленки и стекла.',
    discountPrecentage: 20,
    raiting: 3.6,
    stock: 35,
    price: 160,
    brand: 'Huawei',
    category: "Phone",
    previewImg: './catalog-img/phones/huawei/huaweiP30/huaweiP30-1.jpg',
    images: ['./catalog-img/phones/huawei/huaweiP30/huaweiP30-1.jpg',
    './catalog-img/phones/huawei/huaweiP30/huaweiP30-2.jpg',
    './catalog-img/phones/huawei/huaweiP30/huaweiP30-3.jpg',
    './catalog-img/phones/huawei/huaweiP30/huaweiP30-4.jpg'],
  },
  {
    id: 20,
    title: 'Huawei P40',
    description: 'Huawei P40 оснастили хорошим OLED-экраном с разрешением Full HD+. Это не рекордные цифры, но они обеспечат четкое изображение на дисплее. Панель имеет среднюю, по нынешним мерам, панель, с которой еще более-менее удобно взаимодействовать.',
    discountPrecentage: 5,
    raiting: 4.2,
    stock: 50,
    price: 950,
    brand: 'Huawei',
    category: "Phone",
    previewImg: './catalog-img/phones/huawei/huaweiP40/huaweiP40-1.jpg',
    images: ['./catalog-img/phones/huawei/huaweiP40/huaweiP40-1.jpg',
    './catalog-img/phones/huawei/huaweiP40/huaweiP40-2.jpg',
    './catalog-img/phones/huawei/huaweiP40/huaweiP40-3.jpg',
    './catalog-img/phones/huawei/huaweiP40/huaweiP40-4.jpg',
    './catalog-img/phones/huawei/huaweiP40/huaweiP40-5.jpg'],
  },
  {
    id: 21,
    title: 'Poco F3',
    description: 'Xiaomi Poco F3 имеет большой экран с повышенной частотой обновления 120 Гц, что позволяет комфортнее пользоваться смартфоном. Плавность работы чувствуется практически во всех сценариях использования. Вырез в дисплее практически незаметный. Уровень яркости более чем достаточно, контрастность тоже на высоком уровне, но главное есть функция устранения мерцания.',
    discountPrecentage: 10,
    raiting: 3.7,
    stock: 80,
    price: 350,
    brand: 'Xiaomi Poco',
    category: "Phone",
    previewImg: './catalog-img/phones/poco/pocoF3/pocoF3-1.jpg',
    images: ['./catalog-img/phones/poco/pocoF3/pocoF3-1.jpg',
    './catalog-img/phones/poco/pocoF3/pocoF3-2.jpg',
    './catalog-img/phones/poco/pocoF3/pocoF3-3.jpg'],
  },
  {
    id: 22,
    title: 'Poco X4 Pro',
    description: 'Xiaomi Poco X4 Pro 5G получил достойный AMOLED-дисплей с высокой пиковой яркость около 1200 нит. Он имеет повышенную частоту обновления, включая сенсор, что улучшает реакцию на касания пальца. Панель защищена прочным стеклом Gorilla Glass. Экран лишен поддержки HDR10, но зато цветопередача соответствует цветовому диапазону DCI-P3, что говорит о хорошей точности отражения цветов.',
    discountPrecentage: 10,
    raiting: 3.7,
    stock: 20,
    price: 380,
    brand: 'Xiaomi Poco',
    category: "Phone",
    previewImg: './catalog-img/phones/poco/pocoX4pro/pocoX4pro-1.jpg',
    images: ['./catalog-img/phones/poco/pocoX4pro/pocoX4pro-1.jpg',
    './catalog-img/phones/poco/pocoX4pro/pocoX4pro-2.jpg',
    './catalog-img/phones/poco/pocoX4pro/pocoX4pro-3.jpg',
    './catalog-img/phones/poco/pocoX4pro/pocoX4pro-4.jpg'],
  },
  {
    id: 23,
    title: 'Galaxy A23',
    description: 'Для своей стоимости смартфон показывает неплохие результаты съемки, и детализация, а также четкость на достаточно высоком уровне. Однако мы заметили, что цвета могут выглядеть перенасыщенными. Примеры сверхширокоугольной съемки оказались слабого качества. Уровень шумов оказался высоким, детализация не выдерживает критики, а динамический диапазон ограниченный.',
    discountPrecentage: 15,
    raiting: 3.7,
    stock: 70,
    price: 270,
    brand: 'Samsung',
    category: "Phone",
    previewImg: './catalog-img/phones/samsung/Galaxy A23/Galaxy A23-1.jpeg',
    images: ['./catalog-img/phones/samsung/Galaxy A23/Galaxy A23-1.jpeg',
    './catalog-img/phones/samsung/Galaxy A23/Galaxy A23-2.jpeg'],
  },
  {
    id: 24,
    title: 'Galaxy A52',
    description: 'Смартфон получил обновленную камеру на 64 МП, которая оснащена оптическим стабилизатором. Автономность можно смело назвать сильной стороной Galaxy A52, так как он работает без подзарядки именно столько, сколько ожидаешь получить от батареи емкостью 4500 мАч. Можно смело отправлять на работу и не переживать, что по пути домой телефон разрядится. Заряжается он тоже в пределах нормы – от адаптера питания на 25 Вт он набирает 100% за полтора часа.',
    discountPrecentage: 14,
    raiting: 3.7,
    stock: 80,
    price: 330,
    brand: 'Samsung',
    category: "Phone",
    previewImg: './catalog-img/phones/samsung/Galaxy A52/Galaxy A52-1.jpeg',
    images: ['./catalog-img/phones/samsung/Galaxy A52/Galaxy A52-1.jpeg',
    './catalog-img/phones/samsung/Galaxy A52/Galaxy A52-2.jpeg',
    './catalog-img/phones/samsung/Galaxy A52/Galaxy A52-3.jpeg'],
  },
  {
    id: 25,
    title: 'Xiaomi 11T Pro',
    description: 'Xiaomi 11T Pro имеет дисплей с адаптивной частотой обновления 120 Гц, что позволяет улучшить плавность работы смартфона без существенного ухудшения автономности. Он обладает достаточным разрешением и хорошей точностью передачи цветов. Вырез в дисплее есть, однако дискомфорта он не вызывает. Яркость настраивается автоматически в зависимости от освещения окружающей среды, и в максимальном режиме она достигает показателя более 800 нит, что позволяет без проблем пользоваться смартфоном на улице.',
    discountPrecentage: 18,
    raiting: 3.9,
    stock: 40,
    price: 500,
    brand: 'Xiaomi',
    category: "Phone",
    previewImg: './catalog-img/phones/xiaomi/Xiaomi11TPro/Xiaomi11TPro-1.jpg',
    images: ['./catalog-img/phones/xiaomi/Xiaomi11TPro/Xiaomi11TPro-1.jpg',
    './catalog-img/phones/xiaomi/Xiaomi11TPro/Xiaomi11TPro-2.jpg',
    './catalog-img/phones/xiaomi/Xiaomi11TPro/Xiaomi11TPro-3.jpg',
    './catalog-img/phones/xiaomi/Xiaomi11TPro/Xiaomi11TPro-4.jpg'],
  },
  {
    id: 26,
    title: 'Xiaomi 12 Lite',
    description: 'Xiaomi 12 Lite имеет повышенную частоту дисплея до 120 Гц и частоту работы сенсора до 240 Гц. Это дает очень плавную картинку и практически мгновенную реакцию панели на касания пальца. Последнее дает преимущество в играх, которые требуют быстрой реакции игрока. Дисплей также может похвастаться поддержкой Dolby Vision, что гарантирует отличное качество изображения. Яркость у него тоже на достойном уровне, что означает комфортное использование смартфона на улице. Дневные фотографии лишены заметных дефектов – качество впечатляет. Четкость вполне хорошая, и никаких проблем с детализацией мы не наблюдаем. В то же самое время динамический диапазон оказался широким, а уровень шумов – низкий. Алгоритмы камеры по умолчанию повышают контраст и насыщенность цветов, что вполне характерно для смартфонов этого бренда. Из-за этого может падать детализация в облаках. Не стоит снимать в режиме 108 МП, так как он повышает уровень шумов.',
    discountPrecentage: 10,
    raiting: 4.1,
    stock: 90,
    price: 610,
    brand: 'Xiaomi',
    category: "Phone",
    previewImg: './catalog-img/phones/xiaomi/Xiaomi12Lite/Xiaomi12Lite-1.jpg',
    images: ['./catalog-img/phones/xiaomi/Xiaomi12Lite/Xiaomi12Lite-1.jpg',
    './catalog-img/phones/xiaomi/Xiaomi12Lite/Xiaomi12Lite-2.jpg',
    './catalog-img/phones/xiaomi/Xiaomi12Lite/Xiaomi12Lite-3.jpg',
    './catalog-img/phones/xiaomi/Xiaomi12Lite/Xiaomi12Lite-4.jpg'],
  },
  {
    id: 27,
    title: 'Xiaomi Redmi 9A',
    description: 'Xiaomi Redmi 9A получил обычный для такого недорого смартфона дизайн – пластиковый корпус и простое закаленное стекло, которое защищает дисплей. Оно неплохо справляется со своей задачей, хотя разбить не составляет особого труда. Посередине дисплея имеется U-образный вырез, который не обращает на себя внимания пользователя.',
    discountPrecentage: 10,
    raiting: 3.2,
    stock: 20,
    price: 130,
    brand: 'Xiaomi',
    category: "Phone",
    previewImg: './catalog-img/phones/xiaomi/XiaomiRedmi9A/XiaomiRedmi9A-1.jpg',
    images: ['./catalog-img/phones/xiaomi/XiaomiRedmi9A/XiaomiRedmi9A-1.jpg',
    './catalog-img/phones/xiaomi/XiaomiRedmi9A/XiaomiRedmi9A-2.jpg',
    './catalog-img/phones/xiaomi/XiaomiRedmi9A/XiaomiRedmi9A-3.jpg',
    './catalog-img/phones/xiaomi/XiaomiRedmi9A/XiaomiRedmi9A-4.jpg'],
  },
  {
    id: 28,
    title: 'Apple iPad 10.9',
    description: 'Современный и многофункциональный планшет Apple iPad Air 10.9-INCH 4G 64 ГБ (2020) оснащён большим 10.9-дюймовым экраном, который открывает для вас множество возможностей. Благодаря оптимальным размерам и высокому разрешению в 2360x1640 пикселей вы можете не только наслаждаться просмотром любимых фильмов и сериалов, но и с удобством выполнять на нем другие задачи. Данную модель можно использовать для создания авторских рисунков, собственных логотипов, обработки фотографий и многого другого. К тому же, девайс работает на базе мощного процессора Apple A14 Bionic, который обеспечивает высокую производительность.',
    discountPrecentage: 8,
    raiting: 4.7,
    stock: 50,
    price: 1110,
    brand: 'Apple',
    category: "Tablet",
    previewImg: './catalog-img/tablets/apple/Apple iPad 10,9/pad_10-1.png',
    images: ['./catalog-img/tablets/apple/Apple iPad 10,9/pad_10-1.png',
    './catalog-img/tablets/apple/Apple iPad 10,9/pad_10-2.png'],
  },
  {
    id: 29,
    title: 'Apple iPad Mini (2021)',
    description: 'Новый iPad mini, представленный осенью, стал одной из главных новинок Apple за последнее время. Действительно, из всех линеек компании именно iPad mini, а также MacBook Pro были обновлены наиболее радикально. Модули связи теперь соответствуют актуальным стандартам (Wi-Fi 6, 5G), а вместо разъема Lightning появился USB-C. Тыльная камера научилась снимать в 4К — кстати, для более компактного iPad mini это актуальнее, чем для iPad. Ну и еще всякого по мелочи.',
    discountPrecentage: 10,
    raiting: 4.4,
    stock: 15,
    price: 700,
    brand: 'Apple',
    category: "Tablet",
    previewImg: './catalog-img/tablets/apple/Apple iPad mini 2021/miniPad-1.png',
    images: ['./catalog-img/tablets/apple/Apple iPad mini 2021/miniPad-1.png',
    './catalog-img/tablets/apple/Apple iPad mini 2021/miniPad-2.png',
    './catalog-img/tablets/apple/Apple iPad mini 2021/miniPad-3.png',
    './catalog-img/tablets/apple/Apple iPad mini 2021/miniPad-4.png'],
  },
  {
    id: 30,
    title: 'Apple iPad Pro 12',
    description: 'Особенность этой серии — уникальный чип M1, который также используется в MacBook Pro и Air, Mac mini и iMac. Уникальные технологии чипа обеспечивают высочайшую производительность, а его энергоэффективность позволяет целый день работать без подзарядки. С восьмиядерным центральным процессором можно создавать сложные модели с дополненной реальностью и играть в игры с графикой консольного уровня и высокой частотой обновления кадров. Дисплей Liquid Retina XDR 12,9″ с технологией mini-LED и контрастностью 1 000 000:1 передаёт каждую деталь с невероятной реалистичностью. Он отлично подойдёт для работы с фото и видео HDR или для просмотра любимых фильмов и сериалов, поддерживает самые передовые технологии, такие как широкий цветовой охват, True Tone и ProMotion.',
    discountPrecentage: 5,
    raiting: 4.7,
    stock: 65,
    price: 1200,
    brand: 'Apple',
    category: "Tablet",
    previewImg: './catalog-img/tablets/apple/Apple iPad Pro 12/ipad_pro_2022-1.png',
    images: ['./catalog-img/tablets/apple/Apple iPad Pro 12/ipad_pro_2022-1.png',
    './catalog-img/tablets/apple/Apple iPad Pro 12/ipad_pro_2022-2.png'],
  },
  {
    id: 31,
    title: 'MatePad 11',
    description: 'Новый HUAWEI MatePad 11 — это первый планшет Huawei с дисплеем, поддерживающим частоту обновления 120 Гц, обеспечивающим выдающееся плавное изображение и повышенную скорость отклика, которая лучше, чем когда-либо. Он работает на HarmonyOS 2 и наделяет HUAWEI MatePad 11 совершенно новыми функциями. Рабочий стол нового планшета более организован, чем когда-либо прежде, предлагая пользователям новый способ более эффективного просмотра важной информации.',
    discountPrecentage: 10,
    raiting: 3.9,
    stock: 30,
    price: 520,
    brand: 'Huawei',
    category: "Tablet",
    previewImg: './catalog-img/tablets/huawei/MatePad 11/huawei_matepad_11_1-460x460.jpg',
    images: ['./catalog-img/tablets/huawei/MatePad 11/huawei_matepad_11_1-460x460.jpg',
    './catalog-img/tablets/huawei/MatePad 11/huawei_matepad_11_2-460x460.jpg',
    './catalog-img/tablets/huawei/MatePad 11/huawei_matepad_11_3-460x460 (1).jpg',
    './catalog-img/tablets/huawei/MatePad 11/huawei_matepad_11_4-460x460.jpg'],
  },
  {
    id: 32,
    title: 'MatePad LTE',
    description: 'Дисплей планшета имеет диагональ 10,4 дюйма, разрешение — 2000×1200. Это дает не самую высокую плотность точек — 224 ppi. Лицевая поверхность экрана выполнена в виде стеклянной пластины с зеркально-гладкой поверхностью, устойчивой к появлению царапин. Экран имеет хорошие углы обзора без значительного сдвига цветов даже при больших отклонениях взгляда от перпендикуляра к экрану и без инвертирования оттенков.',
    discountPrecentage: 9,
    raiting: 3.8,
    stock: 35,
    price: 440,
    brand: 'Huawei',
    category: "Tablet",
    previewImg: './catalog-img/tablets/huawei/MatePad LTE/huawei_matepad_harmony_1-460x460.jpg',
    images: ['./catalog-img/tablets/huawei/MatePad LTE/huawei_matepad_harmony_1-460x460.jpg',
    './catalog-img/tablets/huawei/MatePad LTE/huawei_matepad_harmony_2-460x460.jpg',
    './catalog-img/tablets/huawei/MatePad LTE/huawei_matepad_harmony_3-460x460.jpg',
    './catalog-img/tablets/huawei/MatePad LTE/huawei_matepad_harmony_4-460x460.jpg'],
  },
  {
    id: 33,
    title: 'MatePad T10s',
    description: 'Это игровой планшет Huawei Matepad T 10S. Гаджет понравился мне своим классическим дизайном, большим экраном и обширной функциональностью для серфинга в интернете, просмотра ютуб и различных видеороликов. Основная камера с разрешением 5 мегапикселей, съемка видео производится в формате full HD.',
    discountPrecentage: 15,
    raiting: 3.6,
    stock: 50,
    price: 340,
    brand: 'Huawei',
    category: "Tablet",
    previewImg: './catalog-img/tablets/huawei/MatePad T10s/huawei_t10s_1-460x460.jpg',
    images: ['./catalog-img/tablets/huawei/MatePad T10s/huawei_t10s_1-460x460.jpg',
    './catalog-img/tablets/huawei/MatePad T10s/huawei_t10s_2-460x460.jpg',
    './catalog-img/tablets/huawei/MatePad T10s/huawei_t10s_3-460x460.jpg',
    './catalog-img/tablets/huawei/MatePad T10s/huawei_t10s_4-460x460.jpg'],
  },
  {
    id: 34,
    title: 'Apple Watch Series 7',
    description: 'Apple Watch Series 7 – наделены всеми необходимым для комфортного пользования: большим и ярким дисплеем, отличной производительностью, удобными функциями и стильным дизайном. Помимо этого, с их помощью можно делать то, что недоступ­но другим устройствам. Данная модель имеет большой и яркий дисплей, который отображает насыщенное изображение. Совместная работа инженеров и дизайнеров позволила уменьшить рамку по краям дисплея Retina, сделав область для отображения информации больше. Следует также отметить, что они помогают своему обладателю удобно и легко отслеживать активность через систему колец с очками, то есть необходимо быть активным каждый день, например, гулять или выходить на пробежки. К тому же, девайс отличатся наличием таких функциональных возможностей, как ЭКГ, измерение уровня кислорода в крови, мониторинг калорий, мониторинг сна, мониторинг физической активности, постоянное измерение пульса и другие.',
    discountPrecentage: 6,
    raiting: 4.6,
    stock: 40,
    price: 540,
    brand: 'Apple',
    category: "Watch",
    previewImg: './catalog-img/watches/apple/Apple Watch Series 7/S7-1.png',
    images: ['./catalog-img/watches/apple/Apple Watch Series 7/S7-1.png',
    './catalog-img/watches/apple/Apple Watch Series 7/S7-2.png',
    './catalog-img/watches/apple/Apple Watch Series 7/S7-3.png'],
  },
  {
    id: 35,
    title: 'Apple Watch Series 8',
    description: 'Смарт часы Apple Watch Series 8 – это инновационное устройство, оснащенное множеством преимуществом, одной из которых является сенсорный дисплей, отображающий качественные изображения с яркой цветопередачей. Данная модель оснащена емким аккумулятором, позволяющий работать длительное время без подзарядки. К тому же, часы оснащены водонепроницаемой конструкцией, поэтому вы можете спокойно купаться в них в душе, ванной или бассейне. Более того, благодаря беспроводному модулю Bluetooth вы сможете подключить к устройству свой смартфон или планшет. Такая технология позволяет отображать звонки и сообщения на часах, что очень удобно, например, когда телефон находится в другой комнате.',
    discountPrecentage: 5,
    raiting: 4.7,
    stock: 35,
    price: 600,
    brand: 'Apple',
    category: "Watch",
    previewImg: './catalog-img/watches/apple/Apple Watch Series 8/S8-1.jpeg',
    images: ['./catalog-img/watches/apple/Apple Watch Series 8/S8-1.jpeg',
    './catalog-img/watches/apple/Apple Watch Series 8/S8-2.jpeg',
    './catalog-img/watches/apple/Apple Watch Series 8/S8-3.jpeg'],
  },
  {
    id: 36,
    title: 'Apple Watch Ultra',
    description: 'Новые Apple Watch Ultra: главные фишки: Сирена, которую слышно на расстоянии до 190 метров. Усовершенствованное приложение «Компас» с геолокацией и GPS-трекингом. Автономность до 60 часов. Способность выдерживать большое давление воды и понимать, что пользователь погрузился под воду.',
    discountPrecentage: 5,
    raiting: 4.7,
    stock: 50,
    price: 1005,
    brand: 'Apple',
    category: "Watch",
    previewImg: './catalog-img/watches/apple/Apple Watch Ultra/Ultra-1.jpg',
    images: ['./catalog-img/watches/Apple Watch Ultra/Ultra-1.jpg',
    './catalog-img/watches/apple/Apple Watch Ultra/Ultra-2.jpeg',
    './catalog-img/watches/apple/Apple Watch Ultra/Ultra-3.jpeg',
    './catalog-img/watches/apple/Apple Watch Ultra/Ultra-4.jpeg'],
  },
  {
    id: 37,
    title: 'Huawei Watch Fit TIA-B09',
    description: 'Huawei Watch Fit оснастили большим количеством фитнес-функций: здесь можно замерить кислород в крови - довольно актуальная вещь, ведь одним из проявлений 2019-nCoV является понижение SpO2; измерение частоты сердечных сокращений, анализ стресса и сна, возможность делать дыхательные упражнения для расслабления организма. Одна из необычных вещей - анимированные программы тренировки: на большом экране Watch Fit отображается модель человека (мужчины) в полный рост, которая показывает то, как вы должны выполнять те или иные упражнения. А я вот думаю, почему нельзя выбрать пол того, кто будет показывать движения. Опасное явление, на самом деле: в лучшем случае могут обвинить в гендерном неравенстве, а в худшем - в ущемлении прав меньшинств.',
    discountPrecentage: 12,
    raiting: 4.1,
    stock: 20,
    price: 120,
    brand: 'Huawei',
    category: "Watch",
    previewImg: './catalog-img/watches/huawei/Huawei Watch Fit TIA-B09/Fit-1.jpg',
    images: ['./catalog-img/watches/huawei/Huawei Watch Fit TIA-B09/Fit-1.jpg',
    './catalog-img/watches/huawei/Huawei Watch Fit TIA-B09/Fit-2.jpg',
    './catalog-img/watches/huawei/Huawei Watch Fit TIA-B09/Fit-3.jpg'],
  },
  {
    id: 38,
    title: 'Huawei Watch GT Runner',
    description: 'HUAWEI WATCH GT Runner — самая спортивная модель в новой линейке бренда. Часы получили практичный корпус, качественный экран и поддерживают большое количество тренировок на любой вкус. Вендор прокачал опции для бега, поставил высокоточные датчики и позаботился о приличной автономности.',
    discountPrecentage: 10,
    raiting: 4.1,
    stock: 50,
    price: 65,
    brand: 'Huawei',
    category: "Watch",
    previewImg: './catalog-img/watches/huawei/Huawei Watch GT Runner/gt-1.jpg',
    images: ['./catalog-img/watches/huawei/Huawei Watch GT Runner/gt-1.jpg',
    './catalog-img/watches/huawei/Huawei Watch GT Runner/gt-2.jpg',
    './catalog-img/watches/huawei/Huawei Watch GT Runner/gt-3.jpg'],
  },
  {
    id: 39,
    title: 'Huawei Watch GT Runner RUN-B19',
    description: 'Имеется ряд полезных опций именно для спортсменов, таких как создание индивидуального плана тренировок, оценка еженедельной нагрузки, рекомендации, информация об уровне усталости и времени, необходимом для восстановления, интенсивности аэробной и анаэробной нагрузки.',
    discountPrecentage: 10,
    raiting: 4.2,
    stock: 30,
    price: 67,
    brand: 'Huawei',
    category: "Watch",
    previewImg: './catalog-img/watches/huawei/Huawei Watch GT Runner RUN-B19/run-1.jpg',
    images: ['./catalog-img/watches/huawei/Huawei Watch GT Runner RUN-B19/run-1.jpg',
    './catalog-img/watches/huawei/Huawei Watch GT Runner RUN-B19/run-2.jpg',
    './catalog-img/watches/huawei/Huawei Watch GT Runner RUN-B19/run-3.jpg'],
  },
  {
    id: 40,
    title: 'Samsung Galaxy Watch 4',
    description: 'Технические характеристики Galaxy Watch4 Classic 46 мм: Экран: Super AMOLED 1,4" с разрешением 450х450, 330 ppi, защищен Corning Gorilla Glass DX. Процессор: двух ядерный Exynos W920 с частотой 1,8 GHz, техпроцесс 5 нм + графика GPU Mali-G68. Память: 1,5 GB оперативной памяти + 16 GB встроенное хранилище',
    discountPrecentage: 6,
    raiting: 4.7,
    stock: 55,
    price: 280,
    brand: 'Samsung',
    category: "Watch",
    previewImg: './catalog-img/watches/samsung/Samsung Galaxy Watch4/1.jpg',
    images: ['./catalog-img/watches/samsung/Samsung Galaxy Watch4/1.jpg',
    './catalog-img/watches/samsung/Samsung Galaxy Watch4/2.jpg',
    './catalog-img/watches/samsung/Samsung Galaxy Watch4/3.jpg'],
  },
  {
    id: 41,
    title: 'Samsung Galaxy Watch 5',
    description: 'Программное обеспечение работает под управлением Wear OS Powered от Samsung (по сути Wear OS 3 с оболочкой Samsung). Galaxy Watch 5 Pro, появившийся вместе с Watch 5 26 августа, поражает новым дизайном и крутыми функциями, например, пошаговой навигацией. Так же в данной серии был добавлен инфракрасный датчик температуры',
    discountPrecentage: 5,
    raiting: 4.8,
    stock: 50,
    price: 360,
    brand: 'Samsung',
    category: "Watch",
    previewImg: './catalog-img/watches/samsung/Samsung Galaxy Watch5/1.jpg',
    images: ['./catalog-img/watches/samsung/Samsung Galaxy Watch5/1.jpg',
    './catalog-img/watches/samsung/Samsung Galaxy Watch5/2.jpg',
    './catalog-img/watches/samsung/Samsung Galaxy Watch5/3.jpg'],
  },

];

const d = document.createElement('img');
d.src = PRODUCTS[0].previewImg;
document.querySelector('.main__right-product-top')?.appendChild(d);
